name: CI

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "**"
      - "!renovate/**"
      - "!dependabot/**"
    tags:
      - "v**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Setup node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: "20"
          cache: "yarn"

      - run: yarn --immutable

      - run: yarn exec prettier --check ./

      - run: yarn exec tsc --noEmit

      - run: yarn run build

      - run: |
          yarn pack
          tar zxvf package.tgz
        if: ${{ github.event_name == 'push' }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4
        if: ${{ github.event_name == 'push' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./package
          user_name: "github-actions"
          user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          enable_jekyll: false
