name: Node.js Package
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
          cache: "yarn"

      - run: yarn --immutable
      - run: yarn build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Get Previous Tag
        id: tag
        uses: trim21/changelog-previous-tag@master
        with:
          token: ${{ github.token }}
          version-spec: semver

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@b78a3354a01f4a1affb484b9264b506a815c46b1 # v1
        with:
          token: ${{ github.token }}
          fromTag: ${{ github.ref_name }}
          toTag: ${{ env.previousTag }}
          restrictToTypes: feat,fix,revert

      - name: Upload Github Release
        run: gh release create "${GITHUB_REF}" --notes "${CHANGELOG}" $EXTRA_OPTS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGELOG: "${{ steps.changelog.outputs.changes }}"
          EXTRA_OPTS: "${{ env.preRelease == 'true' && '-p' || '' }}"
